### ISSUE TITLE
Data access upgrades

### ISSUE THREAD

**Issue by juansensio** [earthpulse/eotdl#168]
Pierre-Jean Coquard from AGENIUM Space:

We've encountered a number of issues that can make the data retrieving process more complicated than using a third-party API in some cases. I'm not sure of where I should post this kind of user feedback, so I'm sending it directly to you.

    • The size of a downloadable image is limited to 2500 x 2500 pixel, but the bounding box is specified in latitude / longitude. This makes it less obvious to the user whether his request is valid or not. Moreover, in a perspective of creating datasets for machine learning, it could be time-saving to be able to get images just from the centre coordinate of the image and the width and height given in pixel in a single function.

    • When downloading a batch of images, their default name is written as "<type>_<acquisition-date>.tif". As a result, downloading multiple images from the same sensor at the same date will result in overwriting the previous image, since they are all named the same. Adding the option of renaming the output image file in the download function instead of having to change its name between each download would help. 

    • It would be great to have the possibility to download full Sentinel products in order to process a large scale database.

I understand that a some of these limitations are due to how Sentinel Hub API works. However, I think it might be beneficial to implement wrappers with more options to facilitate the access of the available data.

**Comment by fmariv** [comment]
This issue can be closed. In the notebook [11_download_sentinel_imagery](https://github.com/earthpulse/eotdl/blob/main/tutorials/notebooks/11_download_sentinel_imagery.ipynb) the following has been exemplified:
1. How to create a bounding box from coordinates, giving the width and height in pixels and the pixel size.
```
from eotdl.tools import bbox_from_centroid

x = 12.7
y = 41.8

custom_bbox = bbox_from_centroid(x=x, y=y, pixel_size=10, width=512, height=512)
```

2. How to name downloaded images.

```
# This will save the image as `Jaca.tif` as this only downloads one image
download_sentinel_imagery(
    output="data/jaca_bulk",
    time_interval="2020-01-04",
    bounding_box=jaca_bounding_box,
    sensor="sentinel-2-l2a",
    name="Jaca",
)

# This will save the images as `Jaca_<date>.tif` as this downloads several images
download_sentinel_imagery(
    output="data/jaca_bulk",
    time_interval=("2020-01-01", "2020-01-10"),
    bounding_box=jaca_bounding_box,
    sensor="sentinel-2-l2a",
    name="Jaca",
)
```

The option to download an entire product has not been implemented, since the data access method is based on Sentinel Hub.

**Comment by PJagenium** [comment]
Hi, I'm getting back to you about those previous issues.

1. First, the bounding box doesn't seem to work as intended. For example, using the bounding box shown in this notebook to download Sentinel-2 images results in downloading images of size 502 x 495 instead of 512 x 512. 

I believe it has to do with the use of a conversion from the EPSG:4326 (WSG84 projection) to the EPSG:3857 (Web Mercator projection) to get that bounding box in pixel unit and then back to WSG84. The issue here is that the EPSG:3857 is only accurate on the equator. A simple fix would be to rely on local UTM projections instead of the EPSG:3857 : 

```python
def patched_bbox_from_centroid(
    x: Union[int, float],
    y: Union[int, float],
    pixel_size: Union[int, float],
    width: Union[int, float],
    height: Union[int, float],
) -> list:
    """
    Generate a bounding box from a centroid, pixel size and image dimensions.

    Params
    ------
    x: int or float
        x coordinate of the centroid
    y: int or float
        y coordinate of the centroid
    pixel_size: int or float
        pixel size in meters
    width: int or float
        width of the image in pixels
    height: int or float
        height of the image in pixels

    Returns
    -------
    bounding_box: list
        list with the bounding box coordinates
    """
    width_m = width * pixel_size
    heigth_m = height * pixel_size

    # Initialise the transformers
    utm_crs = CRS.get_utm_from_wgs84(y, x).ogc_string()
    from_4326_transformer = Transformer.from_crs("EPSG:4326", utm_crs)
    to_4326_transformer = Transformer.from_crs(utm_crs, "EPSG:4326")

    # Transform the centroid coordinates to meters
    centroid_m = from_4326_transformer.transform(x, y)

    # Calculate the bounding box coordinates
    min_x = centroid_m[0] - width_m / 2
    min_y = centroid_m[1] - heigth_m / 2
    max_x = centroid_m[0] + width_m / 2
    max_y = centroid_m[1] + heigth_m / 2

    # Convert the bounding box coordinates back to degrees
    min_x, min_y = to_4326_transformer.transform(min_x, min_y)
    max_x, max_y = to_4326_transformer.transform(max_x, max_y)

    return [min_y, min_x, max_y, max_x]
```
With that fix, this function will return a bounding box of the correct size all around the globe.


2. The second issue is about the naming of the downloaded images. In most cases, it works as intended, where the date will be added to the name if there are multiple dates available in the chosen range. There is an edge case where if a selected zone is contained within 3 or more Sentinel-2 products for a single date, this will be considered as a bulk download. As a result, the date will be added to the name of the image, even though there is only one final image. 

Here is an example, where the selected zone can be found in 4 different Sentinel-2 products at the same time (T32VPH, T32VUC, T32UPG and T32UUB)

```python
from eotdl.access import download_sentinel_imagery

date = "2022-08-12"
bbox = (12.04609, 55.83039, 12.06563, 55.84236)
download_sentinel_imagery(
    output="outputs",
    time_interval=date,
    bounding_box=bbox,
    sensor="sentinel-2-l2a",
)
```

This makes the naming unpredictable since most of the downloaded images won't have the date added to their name except the few concerned by this problem.

Instead of checking whether it is a bulk download in the eotdl.access.download_sentinel_imagery function, a possible fix would be to check in the eotdl.access.sentinelhub.utils.imagery_from_tmp_to_dir function the number of different images that were really downloaded.
