### ISSUE TITLE
Planet Amazon Rainforest

### ISSUE THREAD

**Issue by earthpulse** [earthpulse/eotdl#8]

**Comment by Schpidi** [comment]
@juansensio I don't seem to have the rights to assign myself

**Comment by Schpidi** [comment]
The competition rules state: "Unless otherwise permitted by the terms of the Competition Website, Participants must use the Data solely for the purpose and duration of the Competition, ..." and "Participants agree to use suitable measures to prevent persons who have not formally agreed to these Competition Rules from gaining access to the Data and agree not to transmit, duplicate, publish, redistribute or otherwise provide or make available the Data to any party not participating in the Competition.". Thus I'll refrain from downloading this data from Kaggle. Maybe we could reach out to Planet directly to get permission to use the data.
